[project]
name = 'propertyX'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1VZ3YGJKKC8JSSWMS4EZDXXJM7QWRBEZ0ZWM64E.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.nft-trait'
[contracts.aptContract]
path = 'contracts/aptContract.clar'
clarity_version = 3
epoch = 3.1

[contracts.nft]
path = 'contracts/nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.nft-prototype]
path = 'contracts/nft-prototype.clar'
clarity_version = 3
epoch = 3.1

[contracts.real-World-Asset-Trait]
path = 'contracts/real-World-Asset-Trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.rws]
path = 'contracts/rws.clar'
clarity_version = 3
epoch = 3.1

[contracts.rws-prototype]
path = 'contracts/rws-prototype.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
